"""Fusion Tool Registry IDs verified with Resolve 21.0.4."""

from enum import StrEnum


class FusionTool(StrEnum):
    """Blackmagic-provided Fusion Tool Registry IDs."""

    ACES_TRANSFORM = "AcesTransform"  # ACES Transform
    ALPHA_DIVIDE = "AlphaDivide"  # Alpha Divide
    ALPHA_MULTIPLY = "AlphaMultiply"  # Alpha Multiply
    ANAGLYPH = "Anaglyph"
    AUTO_DOMAIN = "AutoDomain"  # Auto Domain
    AUTO_GAIN = "AutoGain"  # Auto Gain
    BACKGROUND = "Background"
    BENDER_3D = "Bender3D"  # Bender 3D
    BETTER_RESIZE = "BetterResize"  # Resize
    BITMAP_MASK = "BitmapMask"  # Bitmap
    BLUR = "Blur"
    BRIGHTNESS_CONTRAST = "BrightnessContrast"  # Brightness / Contrast
    BUMP_MAP = "BumpMap"
    B_SPLINE_MASK = "BSplineMask"  # BSpline
    CAMERA_3D = "Camera3D"  # Camera 3D
    CAMERA_SHAKE = "CameraShake"  # Camera Shake
    CHANGE_DEPTH = "ChangeDepth"  # Change Depth
    CHANNEL_BOOLEAN = "ChannelBoolean"  # Channel Booleans
    CHROMATIC_ABERRATION_REMOVAL = "ChromaticAberrationRemoval"  # Chromatic Aberration Removal
    CHROMATIC_ADAPTATION = "ChromaticAdaptation"  # Chromatic Adaptation
    CHROMA_KEYER = "ChromaKeyer"  # Chroma Keyer
    CINEON_LOG = "CineonLog"  # Cineon Log
    CLEAN_PLATE = "CleanPLate"  # Clean Plate
    COLOR_CORRECTOR = "ColorCorrector"  # Color Corrector
    COLOR_CURVES = "ColorCurves"  # Color Curves
    COLOR_GAIN = "ColorGain"  # Color Gain
    COLOR_SPACE = "ColorSpace"  # Color Space
    COLOR_SPACE_TRANSFORM = "ColorSpaceTransform"  # Color Space Transform
    COMBINER = "Combiner"
    COORD_SPACE = "CoordSpace"  # Coordinate Space
    CORNER_POSITIONER = "CornerPositioner"  # Corner Positioner
    CREATE_BUMP_MAP = "CreateBumpMap"  # Create Bump Map
    CREATE_RELIEF_MAP = "CreateReliefMap"  # Create Relief Map
    CROP = "Crop"
    CRYPTOMATTE = "Cryptomatte"
    CUBE_3D = "Cube3D"  # Cube 3D
    CUBE_MAP = "CubeMap"
    CUSTOM = "Custom"  # Custom Tool
    CUSTOM_COLOR_MATRIX = "CustomColorMatrix"  # Color Matrix
    CUSTOM_FILTER = "CustomFilter"  # Custom Filter
    CUSTOM_VERTEX_3D = "CustomVertex3D"  # Custom Vertex 3D
    DAY_SKY = "DaySky"
    DEEP_TO_IMAGE = "DeepToImage"  # Deep To Image
    DEEP_TO_POINTS = "DeepToPoints"  # Deep To Points
    DEFOCUS = "Defocus"
    DELTA_KEYER = "DeltaKeyer"  # Delta Keyer
    DENT = "Dent"
    DEPTH_BLUR = "DepthBlur"  # Depth Blur
    DEPTH_MAP = "DepthMap"  # Depth Map
    DIFFERENCE_KEYER = "DifferenceKeyer"  # Difference Keyer
    DIMENSION_CAMERA_TRACKER = "Dimension.CameraTracker"  # Camera Tracker
    DIMENSION_COPY_AUX = "Dimension.CopyAux"  # Copy Aux
    DIMENSION_DISPARITY = "Dimension.Disparity"  # Disparity
    DIMENSION_DISPARITY_TO_Z = "Dimension.DisparityToZ"  # Disparity To Z
    DIMENSION_GLOBAL_ALIGN = "Dimension.GlobalAlign"  # Global Align
    DIMENSION_NEW_EYE = "Dimension.NewEye"  # New Eye
    DIMENSION_OPTICAL_FLOW = "Dimension.OpticalFlow"  # Optical Flow
    DIMENSION_PLANAR_TRACKER = "Dimension.PlanarTracker"  # Planar Tracker
    DIMENSION_PLANAR_TRANSFORM = "Dimension.PlanarTransform"  # Planar Transform
    DIMENSION_REPAIR_FRAME = "Dimension.RepairFrame"  # Repair Frame
    DIMENSION_SMOOTH_MOTION = "Dimension.SmoothMotion"  # Smooth Motion
    DIMENSION_STEREO_ALIGN = "Dimension.StereoAlign"  # Stereo Align
    DIMENSION_TWEEN = "Dimension.Tween"  # Tween
    DIMENSION_Z_TO_DISPARITY = "Dimension.ZToDisparity"  # Z To Disparity
    DIRECTIONAL_BLUR = "DirectionalBlur"  # Directional Blur
    DISPLACE = "Displace"
    DISPLACE_3D = "Displace3D"  # Displace 3D
    DISSOLVE = "Dissolve"
    DISTORT = "Distort"  # Vector Distortion
    DRIP = "Drip"
    DUPLICATE_3D = "Duplicate3D"  # Duplicate 3D
    DVE = "DVE"
    D_COLOR_CORRECTOR = "dColorCorrector"  # dColor Corrector
    D_CROP = "dCrop"
    D_HOLDOUT = "dHoldout"
    D_MERGE = "dMerge"
    D_RECOLOR = "dRecolor"
    D_RESIZE = "dResize"
    D_TRANSFORM = "dTransform"
    ELLIPSE_MASK = "EllipseMask"  # Ellipse
    ERODE_DILATE = "ErodeDilate"  # Erode / Dilate
    EXPORTER_FBX = "ExporterFBX"  # FBX Exporter
    EXTRUDE_3D = "Extrude3D"  # Extrude 3D
    FALLOFF_OPERATOR = "FalloffOperator"  # Falloff
    FAST_NOISE = "FastNoise"
    FAST_NOISE_TEXTURE_3D = "FastNoiseTexture3D"  # Fast Noise Texture
    FIELDS = "Fields"
    FILE_LUT = "FileLUT"  # File LUT
    FILM_GRAIN = "FilmGrain"  # Film Grain
    FILM_LOOK_CREATOR = "FilmLookCreator"  # Film Look Creator
    FILTER = "Filter"
    FOG = "Fog"
    FOG_3D = "Fog3D"  # Fog 3D
    FUSE_DUPLICATE = "Fuse.Duplicate"  # Duplicate
    FUSE_FLS_COPY_METADATA = "Fuse.FLS_CopyMetadata"  # Copy Metadata
    FUSE_FRAME_AVERAGE = "Fuse.FrameAverage"  # Frame Average
    FUSE_LUT_CUBE_ANALYZER = "Fuse.LUTCubeAnalyzer"  # LUT Cube Analyzer
    FUSE_LUT_CUBE_APPLY = "Fuse.LUTCubeApply"  # LUT Cube Apply
    FUSE_LUT_CUBE_CREATOR = "Fuse.LUTCubeCreator"  # LUT Cube Creator
    FUSE_OCL_RAYS = "Fuse.OCLRays"  # Rays
    FUSE_SET_META_DATA = "Fuse.SetMetaData"  # Set Metadata
    FUSE_SET_META_DATA_TC = "Fuse.SetMetaDataTC"  # Set Time Code
    FUSE_WIRELESS = "Fuse.Wireless"  # Wireless Link
    GAMUT_CONVERT = "GamutConvert"  # Gamut
    GAMUT_LIMITER = "GamutLimiter"  # Gamut Limiter
    GAMUT_MAPPING = "GamutMapping"  # Gamut Mapping
    GLOW = "Glow"
    GRAIN = "Grain"
    GRID_WARP = "GridWarp"  # Grid Warp
    HIGHLIGHT = "Highlight"
    HOT_SPOT = "HotSpot"  # Hot Spot
    HUE_CURVES = "HueCurves"  # Hue Curves
    IMAGE_PLANE_3D = "ImagePlane3D"  # Image Plane 3D
    IMAGE_TO_DEEP = "ImageToDeep"  # Image To Deep
    IMMERSIVE_PATCHER = "ImmersivePatcher"  # Immersive Patcher
    KEY_STRETCHER = "KeyStretcher"  # Keyframe Stretcher
    LAT_LONG_PATCHER = "LatLongPatcher"  # LatLong Patcher
    LAYER_MUXER = "LayerMuxer"  # Layer Muxer
    LAYER_REGEX = "LayerRegex"  # Layer Regex
    LAYER_REMOVER = "LayerRemover"  # Layer Remover
    LENS_DISTORT = "LensDistort"  # Lens Distort
    LETTERBOX = "Letterbox"
    LIGHT_AMBIENT = "LightAmbient"  # Ambient Light
    LIGHT_DIRECTIONAL = "LightDirectional"  # Directional Light
    LIGHT_DOME = "LightDome"  # Dome Light
    LIGHT_POINT = "LightPoint"  # Point Light
    LIGHT_PROJECTOR = "LightProjector"  # Projector 3D
    LIGHT_SPOT = "LightSpot"  # Spot Light
    LIGHT_TRIM = "LightTrim"  # Light Trim
    LOADER = "Loader"
    LOCATOR_3D = "Locator3D"  # Locator 3D
    LUMA_KEYER = "LumaKeyer"  # Luma Keyer
    MAGIC_MASK = "MagicMask"  # Magic Mask
    MANDEL = "Mandel"  # Mandelbrot
    MATTE_CONTROL = "MatteControl"  # Matte Control
    MEDIA_IN = "MediaIn"  # Media In
    MEDIA_OUT = "MediaOut"  # Media Out
    MERGE = "Merge"
    MERGE_3D = "Merge3D"  # Merge 3D
    MTL_BLINN = "MtlBlinn"  # Blinn
    MTL_CHAN_BOOL = "MtlChanBool"  # Channel Boolean
    MTL_COOK_TORRANCE = "MtlCookTorrance"  # CookTorrance
    MTL_MERGE_3D = "MtlMerge3D"  # Material Merge
    MTL_PHONG = "MtlPhong"  # Phong
    MTL_REFLECT = "MtlReflect"  # Reflect
    MTL_STEREO_MIX_3D = "MtlStereoMix3D"  # Stereo Mix
    MTL_WARD = "MtlWard"  # Ward
    MULTI_MERGE = "MultiMerge"
    MULTI_POLY = "MultiPoly"
    MULTI_TEXT = "MultiText"
    NOTE = "Note"
    OBJECT_REMOVAL = "ObjectRemoval"  # Object Removal
    OCIO_CDL_TRANSFORM = "OCIOCDLTransform"  # OCIO CDL Transform
    OCIO_COLOR_SPACE = "OCIOColorSpace"  # OCIO ColorSpace
    OCIO_DISPLAY = "OCIODisplay"  # OCIO Display
    OCIO_FILE_TRANSFORM = "OCIOFileTransform"  # OCIO File Transform
    OVERRIDE_3D = "Override3D"  # Override 3D
    O_GRAF_LOADER = "OGrafLoader"
    PAINT = "Paint"
    PAINT_MASK = "PaintMask"  # Mask Paint
    PANO_MAP = "PanoMap"
    PERSPECTIVE_POSITIONER = "PerspectivePositioner"  # Perspective Positioner
    PLASMA = "Plasma"
    POINT_CLOUD_3D = "PointCloud3D"  # PointCloud 3D
    POLYLINE_MASK = "PolylineMask"  # Polygon
    PSEUDO_COLOR = "PseudoColor"  # Pseudo Color
    P_AVOID = "pAvoid"
    P_BOUNCE = "pBounce"
    P_CHANGE_STYLE = "pChangeStyle"
    P_CUSTOM = "pCustom"
    P_CUSTOM_FORCE = "pCustomForce"
    P_DIRECTIONAL_FORCE = "pDirectionalForce"
    P_EMITTER = "pEmitter"
    P_FLOCK = "pFlock"
    P_FOLLOW = "pFollow"
    P_FRICTION = "pFriction"
    P_GRADIENT_FORCE = "pGradientForce"
    P_IMAGE_EMITTER = "pImageEmitter"
    P_KILL = "pKill"
    P_MERGE = "pMerge"
    P_POINT_FORCE = "pPointForce"
    P_RENDER = "pRender"
    P_SPAWN = "pSpawn"
    P_TANGENT_FORCE = "pTangentForce"
    P_TURBULENCE = "pTurbulence"
    P_VORTEX = "pVortex"
    RANGES_MASK = "RangesMask"  # Ranges
    RANK_FILTER = "RankFilter"  # Rank Filter
    RECTANGLE_MASK = "RectangleMask"  # Rectangle
    RELIEF_MAP = "ReliefMap"  # Relief Map
    RELIGHT = "Relight"
    REMOVE_NOISE = "RemoveNoise"  # Remove Noise
    RENDERER_3D = "Renderer3D"  # Renderer 3D
    REPLACE_MATERIAL_3D = "ReplaceMaterial3D"  # Replace Material 3D
    REPLACE_NORMALS_3D = "ReplaceNormals3D"  # Replace Normals 3D
    REPLICATE_3D = "Replicate3D"  # Replicate 3D
    RIBBON_3D = "Ribbon3D"  # Ribbon 3D
    RUN_COMMAND = "RunCommand"
    SAVER = "Saver"
    SCALE = "Scale"
    SET_CANVAS_COLOR = "SetCanvasColor"  # Set Canvas Color
    SET_DOMAIN = "SetDomain"  # Set Domain
    SHADER = "Shader"
    SHADOW = "Shadow"
    SHAPE_3D = "Shape3D"  # Shape 3D
    SHARPEN = "Sharpen"
    SOFT_CLIP = "SoftClip"
    SOFT_GLOW = "SoftGlow"  # Soft Glow
    SPEED_WARP = "SpeedWarp"  # Speed Warp
    SPHERE_MAP = "SphereMap"
    SPHERICAL_CAMERA_3D = "SphericalCamera3D"  # Spherical Camera
    SPHERICAL_STABILIZER = "SphericalStabilizer"  # Spherical Stabilizer
    SPLITTER = "Splitter"
    SSAO = "SSAO"  # Ambient Occlusion
    SURFACE_ALEMBIC_MESH = "SurfaceAlembicMesh"  # Alembic Mesh 3D
    SURFACE_FBX_MESH = "SurfaceFBXMesh"  # FBX Mesh 3D
    SURFACE_TRACKER = "SurfaceTracker"  # Surface Tracker
    SWITCH = "Switch"
    SWIZZLER = "Swizzler"
    S_BOOLEAN = "sBoolean"
    S_B_SPLINE = "sBSpline"
    S_CHANGE_STYLE = "sChangeStyle"
    S_DUPLICATE = "sDuplicate"
    S_ELLIPSE = "sEllipse"
    S_EXPAND = "sExpand"
    S_GRID = "sGrid"
    S_JITTER = "sJitter"
    S_MERGE = "sMerge"
    S_N_GON = "sNGon"
    S_OUTLINE = "sOutline"
    S_POLYGON = "sPolygon"
    S_RECTANGLE = "sRectangle"
    S_RENDER = "sRender"
    S_STAR = "sStar"
    S_TEXT = "sText"
    S_TRANSFORM = "sTransform"
    TEXTURE = "Texture"
    TEXTURE_2D_OPERATOR = "Texture2DOperator"  # Texture 2D
    TEXTURE_TRANSFORM_OPERATOR = "TextureTransformOperator"  # Texture Transform
    TEXT_3D = "Text3D"  # Text 3D
    TEXT_PLUS = "TextPlus"  # Text+
    TEX_CATCHER = "TexCatcher"  # Catcher
    TEX_GRADIENT = "TexGradient"  # Gradient
    TIME_SPEED = "TimeSpeed"  # Time Speed
    TIME_STRETCHER = "TimeStretcher"  # Time Stretcher
    TRACKER = "Tracker"
    TRAILS = "Trails"
    TRANSFORM = "Transform"
    TRANSFORM_3D = "Transform3D"  # Transform 3D
    TRIANGLE_MASK = "TriangleMask"  # Triangle
    TRIANGULATE_3D = "Triangulate3D"  # Triangulate 3D
    TV = "TV"
    ULTRA_KEYER = "UltraKeyer"  # Ultra Keyer
    UNDERLAY = "Underlay"
    UNSHARP_MASK = "UnsharpMask"  # Unsharp Mask
    UV_MAP = "UVMap"  # UV Map 3D
    U_CAMERA = "uCamera"
    U_CATCHER = "uCatcher"
    U_CYLINDER_LIGHT = "uCylinderLight"  # uCylinder Light
    U_DISK_LIGHT = "uDiskLight"  # uDisk Light
    U_DISTANT_LIGHT = "uDistantLight"  # uDistant Light
    U_DOME_LIGHT = "uDomeLight"  # uDome Light
    U_DUPLICATE = "uDuplicate"
    U_EXPORT = "uExport"
    U_IMAGE_PLANE = "uImagePlane"  # uImage Plane
    U_LOADER = "uLoader"
    U_MATERIAL_X = "uMaterialX"
    U_MERGE = "uMerge"
    U_NORMAL_MAP = "uNormalMap"  # uNormal Map
    U_PROJECTOR = "uProjector"
    U_RECT_LIGHT = "uRectLight"  # uRectangle Light
    U_RENDERER = "uRenderer"
    U_REPLACE_MATERIAL = "uReplaceMaterial"  # uReplace Material
    U_SHADER = "uShader"
    U_SHAPE = "uShape"
    U_SPHERE_LIGHT = "uSphereLight"  # uSphere Light
    U_SWITCH = "uSwitch"
    U_TEXTURE = "uTexture"
    U_TEXTURE_TRANSFORM = "uTextureTransform"  # uTexture Transform
    U_TRANSFORM = "uTransform"
    U_VARIANT = "uVariant"
    U_VISIBILITY = "uVisibility"
    U_VOLUME = "uVolume"
    VARI_BLUR = "VariBlur"
    VECTOR_DENOISE = "VectorDenoise"  # Vector Denoise
    VECTOR_MOTION_BLUR = "VectorMotionBlur"  # Vector Motion Blur
    VECTOR_TRANSFORM = "VectorTransform"  # Vector Transform
    VECTOR_WARP = "VectorWarp"  # Vector Warp
    VOLUME_FOG = "VolumeFog"  # Volume Fog
    VOLUME_MASK = "VolumeMask"  # Volume Mask
    VORTEX = "Vortex"
    WAND_MASK = "WandMask"  # Wand
    WELD_3D = "Weld3D"  # Weld 3D
    WHITE_BALANCE = "WhiteBalance"  # White Balance
    ZTO_WORLD_POS = "ZtoWorldPos"  # Z to WorldPos


class FusionResolveFxTool(StrEnum):
    """Blackmagic Resolve FX Tool Registry IDs exposed in Fusion."""

    ABSTRACTION = "ofx.com.blackmagicdesign.resolvefx.Abstraction"  # Abstraction
    ANALOG_DAMAGE = "ofx.com.blackmagicdesign.resolvefx.AnalogDamage"  # Analog Damage
    APERTURE_DIFFRACTION = "ofx.com.blackmagicdesign.resolvefx.ApertureDiffraction"  # Aperture Diffraction
    BEAUTY = "ofx.com.blackmagicdesign.resolvefx.Beauty"  # Beauty
    BLANKING_FILL = "ofx.com.blackmagicdesign.resolvefx.BlankingFill"  # Blanking Fill
    BLEMISH_REMOVAL = "ofx.com.blackmagicdesign.resolvefx.BlemishRemoval"  # AI Blemish Removal
    BOX_BLUR = "ofx.com.blackmagicdesign.resolvefx.BoxBlur"  # Box Blur
    BURN_AWAY = "ofx.com.blackmagicdesign.resolvefx.BurnAway"  # Burn Away
    CAMERA_SHAKE = "ofx.com.blackmagicdesign.resolvefx.CameraShake"  # Camera Shake
    CINEMATIC_HAZE = "ofx.com.blackmagicdesign.resolvefx.CinematicHaze"  # AI Cinematic Haze
    CINE_FOCUS = "ofx.com.blackmagicdesign.resolvefx.CineFocus"  # AI CineFocus
    COLOR_COMPRESSOR = "ofx.com.blackmagicdesign.resolvefx.ColorCompressor"  # Color Compressor
    COLOR_GENERATOR_PLUGIN = "ofx.com.blackmagicdesign.openfx.ColorGeneratorPlugin"  # Color Generator
    COLOR_PALETTE = "ofx.com.blackmagicdesign.resolvefx.ColorPalette"  # Color Palette
    COLOR_TONE_DIFFUSER = "ofx.com.blackmagicdesign.resolvefx.ColorToneDiffuser"  # ColorTone Diffuser
    CONTRAST_POP = "ofx.com.blackmagicdesign.resolvefx.ContrastPop"  # Contrast Pop
    DCTL = "ofx.com.blackmagicdesign.resolvefx.DCTL"  # DCTL
    DEAD_PIXEL_FIXER_V2 = "ofx.com.blackmagicdesign.resolvefx.DeadPixelFixerV2"  # Dead Pixel Fixer
    DEBAND = "ofx.com.blackmagicdesign.resolvefx.Deband"  # Deband
    DEFLICKER = "ofx.com.blackmagicdesign.resolvefx.Deflicker"  # Deflicker
    DEHAZE = "ofx.com.blackmagicdesign.resolvefx.Dehaze"  # Dehaze
    DENT = "ofx.com.blackmagicdesign.resolvefx.Dent"  # Dent
    DESPILL_PLUGIN = "ofx.com.blackmagicdesign.resolvefx.DespillPlugin"  # Despill
    DETAIL_RECOVERY = "ofx.com.blackmagicdesign.resolvefx.DetailRecovery"  # Detail Recovery
    DIRECTIONAL_BLUR = "ofx.com.blackmagicdesign.resolvefx.DirectionalBlur"  # Directional Blur
    DROP_SHADOW = "ofx.com.blackmagicdesign.resolvefx.DropShadow"  # Drop Shadow
    DUST_BUSTER_V2 = "ofx.com.blackmagicdesign.resolvefx.DustBusterV2"  # Dust Buster
    EDGE_DETECT = "ofx.com.blackmagicdesign.resolvefx.EdgeDetect"  # Edge Detect
    EMBOSS = "ofx.com.blackmagicdesign.resolvefx.Emboss"  # Emboss
    FALSE_COLOR = "ofx.com.blackmagicdesign.resolvefx.FalseColor"  # False Color
    FILM_DAMAGE = "ofx.com.blackmagicdesign.resolvefx.FilmDamage"  # Film Damage
    FILM_GRAIN = "ofx.com.blackmagicdesign.resolvefx.FilmGrain"  # Film Grain
    FILM_LOOK = "ofx.com.blackmagicdesign.resolvefx.FilmLook"  # Film Look Creator
    FLICKER_ADDITION = "ofx.com.blackmagicdesign.resolvefx.FlickerAddition"  # Flicker Addition
    FRAME_REPLACER = "ofx.com.blackmagicdesign.resolvefx.FrameReplacer"  # Frame Replacer
    GAUSSIAN_BLUR = "ofx.com.blackmagicdesign.resolvefx.GaussianBlur"  # Gaussian Blur
    GLOW = "ofx.com.blackmagicdesign.resolvefx.Glow"  # Glow
    GRID = "ofx.com.blackmagicdesign.resolvefx.Grid"  # Grid
    HALATION_PLUGIN = "ofx.com.blackmagicdesign.resolvefx.HalationPlugin"  # Halation
    INVERT_COLOR = "ofx.com.blackmagicdesign.resolvefx.InvertColor"  # Invert Color
    JPEG_DAMAGE = "ofx.com.blackmagicdesign.resolvefx.JPEGDamage"  # JPEG Damage
    LENS_BLUR = "ofx.com.blackmagicdesign.resolvefx.LensBlur"  # Lens Blur
    LENS_DISTORTION = "ofx.com.blackmagicdesign.resolvefx.LensDistortion"  # Lens Distortion
    LENS_FLARE_V2 = "ofx.com.blackmagicdesign.resolvefx.LensFlareV2"  # Lens Flare
    LENS_REFLECTIONS = "ofx.com.blackmagicdesign.resolvefx.LensReflections"  # Lens Reflections
    LIGHTRAY = "ofx.com.blackmagicdesign.resolvefx.Lightray"  # Light Rays
    MIRROR = "ofx.com.blackmagicdesign.resolvefx.Mirror"  # Mirrors
    MOSAIC_BLUR = "ofx.com.blackmagicdesign.resolvefx.MosaicBlur"  # Mosaic Blur
    MOTION_BLUR = "ofx.com.blackmagicdesign.resolvefx.MotionBlur"  # Motion Blur
    MOTION_TRAILS = "ofx.com.blackmagicdesign.resolvefx.MotionTrails"  # Motion Trails
    NOISE_REDUCTION = "ofx.com.blackmagicdesign.resolvefx.NoiseReduction"  # Noise Reduction
    NVIDIA_RTXHDR = "ofx.com.blackmagicdesign.resolvefx.NvidiaRTXHDR"  # NVIDIA RTX Video HDR
    OFXHSL_KEYER = "ofx.com.blackmagicdesign.resolvefx.OFXHSLKeyer"  # HSL Keyer
    OFX_3D_KEYER_V2 = "ofx.com.blackmagicdesign.resolvefx.OFX3DKeyerV2"  # 3D Keyer
    OFX_LUMA_KEYER = "ofx.com.blackmagicdesign.resolvefx.OFXLumaKeyer"  # Luma Keyer
    PATCH_REPLACER = "ofx.com.blackmagicdesign.resolvefx.PatchReplacer"  # Patch Replacer
    PICTURE_IN_PICTURE = "ofx.com.blackmagicdesign.resolvefx.PictureInPicture"  # Picture In Picture
    PRISM_BLUR = "ofx.com.blackmagicdesign.resolvefx.PrismBlur"  # Prism Blur
    RADIAL_BLUR = "ofx.com.blackmagicdesign.resolvefx.RadialBlur"  # Radial Blur
    RELIGHT = "ofx.com.blackmagicdesign.resolvefx.Relight"  # AI Relight
    RIPPLE = "ofx.com.blackmagicdesign.resolvefx.Ripple"  # Ripples
    SCANLINE_V2 = "ofx.com.blackmagicdesign.resolvefx.ScanlineV2"  # Scanlines
    SHARPEN = "ofx.com.blackmagicdesign.resolvefx.Sharpen"  # Sharpen
    SHARPEN_EDGE_PLUGIN = "ofx.com.blackmagicdesign.resolvefx.SharpenEdgePlugin"  # Sharpen Edges
    SHRINK_AND_GROW = "ofx.com.blackmagicdesign.resolvefx.ShrinkAndGrow"  # Alpha Matte Shrink and Grow
    SKETCH = "ofx.com.blackmagicdesign.resolvefx.Sketch"  # Pencil Sketch
    SMEAR = "ofx.com.blackmagicdesign.resolvefx.Smear"  # Smear
    SOFT_SHARPEN_SKIN = "ofx.com.blackmagicdesign.resolvefx.SoftSharpenSkin"  # Soften and Sharpen
    SPLIT_TONE = "ofx.com.blackmagicdesign.resolvefx.SplitTone"  # Split Tone
    STOP_MOTION = "ofx.com.blackmagicdesign.resolvefx.StopMotion"  # Stop Motion
    STYLIZE = "ofx.com.blackmagicdesign.resolvefx.Stylize"  # AI Stylize
    TEXTURE_POP = "ofx.com.blackmagicdesign.resolvefx.TexturePop"  # Texture Pop
    TILT_SHIFT_BLUR = "ofx.com.blackmagicdesign.resolvefx.TiltShiftBlur"  # Tilt-Shift Blur
    TRANSFORM = "ofx.com.blackmagicdesign.resolvefx.Transform"  # Transform
    ULTRA_SHARPEN = "ofx.com.blackmagicdesign.resolvefx.UltraSharpen"  # AI UltraSharpen
    VIDEO_COLLAGE = "ofx.com.blackmagicdesign.resolvefx.VideoCollage"  # Video Collage
    VIDEO_RESTORATION = "ofx.com.blackmagicdesign.resolvefx.VideoRestoration"  # Automatic Dirt Removal
    VIGNETTE = "ofx.com.blackmagicdesign.resolvefx.Vignette"  # Vignette
    VORTEX = "ofx.com.blackmagicdesign.resolvefx.Vortex"  # Vortex
    WARPER = "ofx.com.blackmagicdesign.resolvefx.Warper"  # Warper
    WATERCOLOR = "ofx.com.blackmagicdesign.resolvefx.Watercolor"  # Watercolor
    WAVINESS = "ofx.com.blackmagicdesign.resolvefx.Waviness"  # Waviness
    ZOOM_BLUR = "ofx.com.blackmagicdesign.resolvefx.ZoomBlur"  # Zoom Blur
