"""Constants required only by the Countdown V2 regression script."""

FUSION_PAGE_STR = "fusion"

PRJ_GAMMA_STR_ST2084 = "ST2084"
PRJ_GAMMA_STR_GAMMA24 = "Gamma 2.4"
PRJ_COLOR_SPACE_REC2020 = "Rec.2020"
PRJ_COLOR_SPACE_REC709 = "Rec.709"
PRJ_COLOR_SPACE_P3D65 = "P3-D65"

OUT_FILE_EXTENSTION_MOV = "mov"
OUT_FILE_EXTENSTION_EXR = "exr"
OUT_FILE_EXTENSTION_DPX = "dpx"
OUT_FILE_EXTENSTION_TIFF = "tif"
OUT_FILE_EXTENSTION_PNG = "png"
STILL_SEQ_FILE_EXTENTION_LIST = ["dpx", "tif", "png", "exr"]

CODEC_APPLE_PRORES_4444 = "ProRes4444"
CODEC_DPX_RGB_10_BITS = "RGB10"
CODEC_EXR_RGB_HALF = "RGBHalf"
CODEC_H264_NVIDIA = "H264_NVIDIA"
CODEC_H265_NVIDIA = "H265_NVIDIA"
CODEC_PNG_RGB_16_BITS = "RGB16"
CODEC_TIF_RGB_16_BITS = "RGB16"
